# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.define "roletestingvm" do |roletestingvm| end

  config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
  end

  # Ensure python is installed on Ubuntu 16.04, so we can use Ansible:
  config.vm.provision "shell",
    inline: "sudo apt-get install -y python-minimal"


  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../tests/test-roletemplate.yml"
    ansible.verbose = "vv"
    ansible.groups = {
      "test" => ["roletestingvm"],
      }
  end
 
  if Vagrant.has_plugin?("vagrant-cachier")
    # Configure cached packages to be shared between instances of the same base box.
    # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
    config.cache.scope = :box
  end
end
